version: "3"
services:
  polaris:
    image: polarismesh/polaris-server:latest
    container_name: polaris-server
    restart: always
    ports:
      - "8090:8090"
      - "8091:8091"
      - "9090:9090"
      - "9091:9091"
    volumes:
      - "./config/polaris-server.yaml:/root/polaris-server.yaml"